export const CHANGE_ROUTE = "ROUTE/CHANGE_ROUTE";
// products
export const ADD_PRODUCT = "PRODUCTS/ADD_PRODUCT";
export const REQUEST_ADD_PRODUCT = "PRODUCTS/REQUEST_ADD_PRODUCT";
export const UPDATE_PRODUCTS = "PRODUCTS/UPDATE_PRODUCTS";
export const UPDATE_SINGLE_PRODUCT = "PRODUCTS/UPDATE_SINGLE_PRODUCT";
export const REQUEST_UPDATE_SINGLE_PRODUCT =
  "PRODUCTS/REQUEST_UPDATE_SINGLE_PRODUCT";
export const REQUEST_PRODUCTS = "PRODUCTS/REQUEST_POSTS";
export const FETCH_PRODUCTS = "PRODUCTS/FETCH_PRODUCTS";
export const REQUEST_SELECTED_PRODUCT = "PRODUCTS/REQUEST_SELECTED_PRODUCT";
export const FETCH_SELECTED_PRODUCT = "PRODUCTS/FETCH_SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "PRODUCTS/REMOVE_SELECTED_PRODUCT";
export const DELETE_PRODUCT = "PRODUCTS/DELETE_PRODUCT";
export const REQUEST_DELETE_PRODUCT = "PRODUCTS/REQUEST_DELETE_PRODUCT";
export const ADD_CATEGORY = "PRODUCTS/ADD_CATEGORY";
export const FETCH_CATEGORIES = "PRODUCTS/FETCH_CATEGORIES";
export const REQUEST_CATEGORIES = "PRODUCTS/REQUEST_CATEGORIES";
// auth
export const REQUEST_LOGIN = "AUTH/REQUEST_LOGIN";
export const LOGIN = "AUTH/LOGIN";
export const LOGOUT = "AUTH/LOGOUT";
export const REGISTER = "AUTH/REGISTER";
export const SET_USER = "AUTH/SET_USER";
export const CHECK_AUTH = "AUTH/CHECK_AUTH";
export const INITIALIZING = "AUTH/INITIALIZING";
// app
export const SHOW_MODAL = "APP/SHOW_MODAL";
export const HIDE_MODAL = "APP/HIDE_MODAL";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
// cart
export const REQUEST_ADD_PRODUCT_TO_CART = "CART/REQUEST_ADD_PRODUCT_TO_CART";
export const ADD_TO_CART = "CART/ADD_TO_CART";
export const REMOVE_FROM_CART = "CART/REMOVE_FROM_CART";
export const UPDATE_CART = "CART/UPDATE_CART";
export const CLEAR_CART = "CART/CLEAR_CART";
export const CHECKOUT = "CART/CHECKOUT";
export const FETCH_CART = "CART/FETCH_CART";
export const REQUEST_CART = "CART/REQUEST_CART";
export const REQUEST_UP_QUANTITY = "CART/REQUEST_UP_QUANTITY";
export const UP_QUANTITY = "CART/UP_QUANTITY";
export const REQUEST_DOWN_QUANTITY = "CART/REQUEST_DOWN_QUANTITY";
export const DOWN_QUANTITY = "CART/DOWN_QUANTITY";
